In [1]:
from pycaret.classification import *
from sklearn.model_selection import train_test_split

import pandas as pd
import os

In [2]:
ROOT_DIR = "../data"
RANDOM_STATE = 200

train_data = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))

df_normal = train_data[train_data["target"] == "Normal"]
df_abnormal = train_data[train_data["target"] == "AbNormal"]

normal_ratio = 1.0

num_normal = len(df_normal)
num_abnormal = len(df_abnormal)

## under sampling
df_normal = df_normal.sample(n=int(num_abnormal * normal_ratio), replace=False, random_state=RANDOM_STATE)
df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)


# df_train, df_val = train_test_split(
#     df_concat,
#     test_size=0.3,
#     stratify=df_concat["target"],
#     random_state=RANDOM_STATE,
# )

In [3]:
df_concat.tail()

,Wip Line_Dam,Process Desc._Dam,Equipment_Dam,Model.Suffix_Dam,Workorder_Dam,Insp. Seq No._Dam,Insp Judge Code_Dam,CURE END POSITION X Collect Result_Dam,CURE END POSITION X Unit Time_Dam,CURE END POSITION X Judge Value_Dam,...,Production Qty Collect Result_Fill2,Production Qty Unit Time_Fill2,Production Qty Judge Value_Fill2,Receip No Collect Result_Fill2,Receip No Unit Time_Fill2,Receip No Judge Value_Fill2,WorkMode Collect Result_Fill2,WorkMode Unit Time_Fill2,WorkMode Judge Value_Fill2,target
4695,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,4B1XE009-1,1,OK,240.0,NaN,NaN,...,1,NaN,NaN,9,NaN,NaN,1,NaN,NaN,AbNormal
4696,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3G1XC632-1,1,OK,240.0,NaN,NaN,...,60,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
4697,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334502,3K1X7331-1,1,OK,1000.0,NaN,NaN,...,164,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
4698,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3G1XA615-2,1,OK,240.0,NaN,NaN,...,252,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
4699,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3G1XA501-1,1,OK,240.0,NaN,NaN,...,320,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal

In [4]:
setup_clf = setup(data=df_concat, target="target", train_size=0.7, session_id=333, fold_shuffle=True)

In [7]:
model = compare_models(sort='F1', fold=10, n_select=10)

In [8]:
tuned_model = [tune_model(i) for i in model]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [9]:
tuned_model

[RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight={},
                        criterion='entropy', max_depth=1, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0001, min_samples_leaf=5,
                        min_samples_split=5, min_weight_fraction_leaf=0.0,
                        monotonic_cst=None, n_estimators=200, n_jobs=-1,
                        oob_score=False, random_state=333, verbose=0,
                        warm_start=False),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                      class_weight='balanced_subsample', criterion='entropy',
                      max_depth=7, max_features='log2', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0,
                      min_samples_leaf=3, min_samples_split=7,
                      min_weight_fraction_leaf=0.0, monotonic_cst=None,
                      n_estimators=140, n_jobs=-1, oob_score=False,
                      random_state=333, verbose=0, warm_start=False),
 RidgeClassifier(alpha=9.86, class_weight=None, copy_X=True, fit_intercept=False,
                 max_iter=None, positive=False, random_state=333, solver='auto',
                 tol=0.0001),
 GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.0005, loss='log_loss', max_depth=9,
                            max_features='sqrt', max_leaf_nodes=None,
                            min_impurity_decrease=0.4, min_samples_leaf=3,
                            min_samples_split=7, min_weight_fraction_leaf=0.0,
                            n_estimators=150, n_iter_no_change=None,
                            random_state=333, subsample=0.25, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 LGBMClassifier(bagging_fraction=0.6, bagging_freq=5, boosting_type='gbdt',
                class_weight=None, colsample_bytree=1.0, feature_fraction=0.8,
                importance_type='split', learning_rate=0.2, max_depth=-1,
                min_child_samples=61, min_child_weight=0.001, min_split_gain=0.6,
                n_estimators=120, n_jobs=-1, num_leaves=6, objective=None,
                random_state=333, reg_alpha=5, reg_lambda=0.01, subsample=1.0,
                subsample_for_bin=200000, subsample_freq=0),
 LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                            priors=None, shrinkage=None, solver='svd',
                            store_covariance=False, tol=0.0001),
 AdaBoostClassifier(algorithm='SAMME', estimator=None, learning_rate=0.1,
                    n_estimators=290, random_state=333),
 DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                        max_depth=8, max_features=1.0, max_leaf_nodes=None,
                        min_impurity_decrease=0, min_samples_leaf=3,
                        min_samples_split=7, min_weight_fraction_leaf=0.0,
                        monotonic_cst=None, random_state=333, splitter='best'),
 GaussianNB(priors=None, var_smoothing=1e-09),
 LogisticRegression(C=8.251, class_weight='balanced', dual=False,
                    fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                    max_iter=1000, multi_class='auto', n_jobs=None, penalty='l2',
                    random_state=333, solver='lbfgs', tol=0.0001, verbose=0,
                    warm_start=False)]

In [30]:
a = [tuned_model[0], tuned_model[1], tuned_model[3], tuned_model[4], tuned_model[7]]
a

[RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight={},
                        criterion='entropy', max_depth=1, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0001, min_samples_leaf=5,
                        min_samples_split=5, min_weight_fraction_leaf=0.0,
                        monotonic_cst=None, n_estimators=200, n_jobs=-1,
                        oob_score=False, random_state=333, verbose=0,
                        warm_start=False),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                      class_weight='balanced_subsample', criterion='entropy',
                      max_depth=7, max_features='log2', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0,
                      min_samples_leaf=3, min_samples_split=7,
                      min_weight_fraction_leaf=0.0, monotonic_cst=None,
                      n_estimators=140, n_jobs=-1, oob_score=False,
                      random_state=333, verbose=0, warm_start=False),
 GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.0005, loss='log_loss', max_depth=9,
                            max_features='sqrt', max_leaf_nodes=None,
                            min_impurity_decrease=0.4, min_samples_leaf=3,
                            min_samples_split=7, min_weight_fraction_leaf=0.0,
                            n_estimators=150, n_iter_no_change=None,
                            random_state=333, subsample=0.25, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 LGBMClassifier(bagging_fraction=0.6, bagging_freq=5, boosting_type='gbdt',
                class_weight=None, colsample_bytree=1.0, feature_fraction=0.8,
                importance_type='split', learning_rate=0.2, max_depth=-1,
                min_child_samples=61, min_child_weight=0.001, min_split_gain=0.6,
                n_estimators=120, n_jobs=-1, num_leaves=6, objective=None,
                random_state=333, reg_alpha=5, reg_lambda=0.01, subsample=1.0,
                subsample_for_bin=200000, subsample_freq=0),
 DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                        max_depth=8, max_features=1.0, max_leaf_nodes=None,
                        min_impurity_decrease=0, min_samples_leaf=3,
                        min_samples_split=7, min_weight_fraction_leaf=0.0,
                        monotonic_cst=None, random_state=333, splitter='best')]

In [23]:
blended_soft = blend_models(estimator_list=a,
                       fold=10,
                       method="hard",
                       optimize="F1")

In [24]:
final_model = finalize_model(blended_soft)
evaluate_model(final_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [25]:
test_data = pd.read_csv(os.path.join(ROOT_DIR, "test.csv"))

train_columns = train_data.columns
test_data = test_data[train_columns]

df_test_x = test_data.drop(columns=['target'])

In [26]:
test_pred = predict_model(final_model, data=df_test_x)
test_pred

[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6

,Wip Line_Dam,Process Desc._Dam,Equipment_Dam,Model.Suffix_Dam,Workorder_Dam,Insp. Seq No._Dam,Insp Judge Code_Dam,CURE END POSITION X Collect Result_Dam,CURE END POSITION X Unit Time_Dam,CURE END POSITION X Judge Value_Dam,...,Production Qty Collect Result_Fill2,Production Qty Unit Time_Fill2,Production Qty Judge Value_Fill2,Receip No Collect Result_Fill2,Receip No Unit Time_Fill2,Receip No Judge Value_Fill2,WorkMode Collect Result_Fill2,WorkMode Unit Time_Fill2,WorkMode Judge Value_Fill2,prediction_label
0,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,3J1XF767-1,1,OK,1000.0,NaN,NaN,...,195,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
1,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,4B1XD472-2,1,OK,1000.0,NaN,NaN,...,14,NaN,NaN,256,NaN,NaN,1,NaN,NaN,Normal
2,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3H1XE355-1,1,OK,240.0,NaN,NaN,...,98,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
3,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,3L1XA128-1,1,OK,1000.0,NaN,NaN,...,14,NaN,NaN,0,NaN,NaN,1,NaN,NaN,Normal
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,4A1XA639-1,1,OK,240.0,NaN,NaN,...,1,NaN,NaN,215,NaN,NaN,1,NaN,NaN,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17356,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,3K1XB597-1,1,OK,1000.0,NaN,NaN,...,14,NaN,NaN,131,NaN,NaN,1,NaN,NaN,AbNormal
17357,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334501,4A1XB974-1,1,OK,1000.0,NaN,NaN,...,12,NaN,NaN,279,NaN,NaN,1,NaN,NaN,Normal
17358,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3L1XA998-1,1,OK,240.0,NaN,NaN,...,4,NaN,NaN,66,NaN,NaN,1,NaN,NaN,AbNormal
17359,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1XC376-1,1,OK,240.0,NaN,NaN,...,117,NaN,NaN,1,NaN,NaN,0,NaN,NaN,AbNormal
17360,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3J1XC756-1,1,OK,240.0,NaN,NaN,...,71,NaN,NaN,1,NaN,NaN,0,NaN,NaN,Normal

In [27]:
df_sub = pd.read_csv("../data/submission.csv")
df_sub["target"] = test_pred["prediction_label"]
df_sub.to_csv("../data/automl/submission-3.csv", index=False)

In [29]:
test_pred.to_csv('a.csv')